name: 'Install fabric'
description: 'Install dependencies from cache between different node versions'
inputs:
  node-version:
    required: true
    description: 'the node version'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js v${{ inputs.node-version }}
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: npm-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ inputs.node-version }}
    - run: npm ci --audit false --fund false
      shell: bash
