name: 'Build fabric'
description: 'Build fabric and cache result per commit'
runs:
  using: 'composite'
  steps:
    - name: Get cache build
      if: github.event_name == 'pull_request'
      id: build-cache
      uses: actions/cache@2cdf405574d6ef1f269b2803b4b3e6eab1cceb8b # v4.2.4
      with:
        path: |
          ./dist
          ./dist-extensions
        key: build-${{ github.event.pull_request.head.sha }}
    - name: Build fabric.js dist folder
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: npm run build -- -f
      shell: bash
