name: 'Build fabric'
description: 'Build fabric and cache result per commit'
runs:
  using: 'composite'
  steps:
    - name: Get cache build
      if: github.event_name == 'pull_request'
      id: build-cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ./dist
          ./dist-extensions
        key: build-${{ github.event.pull_request.head.sha }}
    - name: Build fabric.js dist folder
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: npm run build -- -f
      shell: bash
