//= require "HEADER"

//= require "lib/cufon"
//= require "lib/json2"

//= require "src/log"
//= require "src/util"
//= require "src/parser"
//= require "src/gradient"
//= require "src/point.class"
//= require "src/intersection.class"
//= require "src/color.class"

//= require "src/canvas.class"
//= require "src/canvas.animation"
//= require "src/canvas.serialization"

//= require "src/object.class"
//= require "src/line.class"
//= require "src/circle.class"
//= require "src/triangle.class"
//= require "src/ellipse.class"
//= require "src/rect.class"
//= require "src/polyline.class"
//= require "src/polygon.class"
//= require "src/path.class"
//= require "src/path_group.class"
//= require "src/group.class"
//= require "src/text.class"
//= require "src/image.class"