sonar.projectKey=fabricjs_fabric.js
sonar.organization=fabricjs


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=fabric.js
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src,extensions,fabric.ts,index.node.ts,index.ts
sonar.exclusions=dist-extensions/**/*,dist/**/*,**/*.spec.ts,e2e/**/*,.codesandbox/**/*
sonar.test.inclusions=**/*.spec.*,**/*.test.*
sonar.tests=src,extensions

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.projectBaseDir=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./.nyc_output/lcov.info
