name: ðŸ› Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: >
        Thank you for wanting to create an issue in this repository. 

        Before you do, please ensure you are filing the issue in the right
        place.  For anything else (such as questions) use
        [Discussions](https://github.com/fabricjs/fabric.js/discussions).
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: >-
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/fabricjs/fabric.js/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: >-
            I have read and followed the [Contributing
            Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
          required: true
        - label: >-
            I have read and followed the [Issue Tracker
            Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
          required: true
        - label: I have searched and referenced existing issues and discussions
          required: true
        - label: I am filing a **BUG** report.
          required: true
        - label: >-
            I have managed to reproduce the bug **after** upgrading to the
            **latest** version
          required: true
        - label: I have created an accurate and minimal reproduction
          required: true
  - type: dropdown
    id: _version
    attributes:
      label: Version
      description: >-
        If you are working on a version below latest you should upgrade to
        latest before filing a bug report, your issue might have been resolved
        already.
      options:
        - 6.0.0-beta4
        - 6.0.0-beta3
        - 6.0.0-beta1
        - 5.3.0
        - 5.2.4
        - 5.2.2
        - 5.2.1
        - 5.1.0
        - 5.0.0
        - 4.6.0
        - 4.5.1
        - 4.5.0
        - 4.4.0
        - 4.3.1
        - 4.3.0
        - 4.2.0
        - 4.1.0
        - 4.0.0
    validations:
      required: true
  - type: dropdown
    id: environments
    attributes:
      label: In What environments are you experiencing the problem?
      description: >-
        checkout the [supported
        browsers](https://github.com/fabricjs/fabric.js/blob/master/README.md#supported-browsersenvironments)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Opera
        - Microsoft Edge
        - Node.js
  - type: dropdown
    id: _node_version
    attributes:
      label: Node Version (if applicable)
      description: Provide the version if the bug occurs in Node.js
      options:
        - 20.1.0
        - 20.0.0
        - 19.8.1
        - 19.8.0
        - 19.7.0
        - 19.6.1
        - 19.6.0
        - 19.5.0
        - 19.4.0
        - 19.3.0
        - 19.2.0
        - 19.1.0
        - 19.0.1
        - 19.0.0
        - 18.16.0
        - 18.15.0
        - 18.14.2
        - 18.14.1
        - 18.14.0
        - 18.13.0
        - 18.12.1
        - 18.12.0
        - 18.11.0
        - 18.10.0
        - 18.9.1
        - 18.9.0
        - 18.8.0
        - 18.7.0
        - 18.6.0
        - 18.5.0
        - 18.4.0
        - 18.3.0
        - 18.2.0
        - 18.1.0
        - 18.0.0
        - 17.9.1
        - 17.7.2
        - 17.7.1
        - 17.7.0
        - 17.6.0
        - 17.5.0
        - 17.4.0
        - 17.3.1
        - 17.3.0
        - 17.2.0
        - 17.1.0
        - 17.0.1
        - 17.0.0
        - 16.20.0
        - 16.19.1
        - 16.19.0
        - 16.18.1
        - 16.18.0
        - 16.17.1
        - 16.17.0
        - 16.16.0
        - 16.15.1
        - 16.15.0
        - 16.14.2
        - 16.14.1
        - 16.14.0
        - 16.13.2
        - 16.13.1
        - 16.13.0
        - 16.12.0
        - 16.11.1
        - 16.11.0
        - 16.10.0
        - 16.9.1
        - 16.9.0
        - 16.8.0
        - 16.7.0
        - 16.6.2
        - 16.6.1
        - 16.6.0
        - 16.5.0
        - 16.4.1
        - 16.4.0
        - 16.3.0
        - 16.1.0
        - 16.0.0
        - 15.14.0
        - 15.12.0
        - 15.10.0
        - 15.8.0
        - 15.7.0
        - 15.4.0
        - 15.3.0
        - 15.2.1
        - 15.2.0
        - 15.1.0
        - 15.0.1
        - 15.0.0
        - 14.21.3
        - 14.21.2
        - 14.21.0
        - 14.20.1
        - 14.20.0
        - 14.19.3
        - 14.19.2
        - 14.19.1
        - 14.19.0
        - 14.18.3
        - 14.18.2
        - 14.18.1
        - 14.18.0
        - 14.17.6
        - 14.17.5
        - 14.17.4
        - 14.17.3
        - 14.17.2
        - 14.17.1
        - 14.16.1
        - 14.16.0
        - 14.15.2
        - 14.15.1
        - 14.15.0
        - 14.14.0
        - 14.13.1
        - 14.13.0
        - 14.12.0
        - 14.11.0
        - 14.10.1
        - 14.10.0
        - 14.9.0
        - 14.8.0
        - 14.7.0
        - 14.6.0
        - 14.5.0
        - 14.4.0
        - 14.3.0
        - 14.2.0
        - 14.1.0
        - 14.0.0
    validations:
      required: false
  - type: input
    id: reproduction_link
    attributes:
      label: Link To Reproduction
      description: >
        A good reproduction helps us UNDERSTAND your issue, find the bug and fix
        it quickly.

        Take the time and put effort into making your reproduction accurate and
        minimal.

        Use the following reproduction templates:

        - [Next template >=
        `v6`](https://codesandbox.io/p/sandbox/fabric-nextjs-sandbox-forked-h6qdh3?file=%2FREADME.md)
        for browser and node reproductions, **preferred**

        - [Vanilla template >=
        `v6`](https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-e5r48u?file=%2FREADME.md),
        [Vanilla template <
        `v6`](https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-v92h26?file=%2FREADME.md)
        for browser reproductions

        - [Node template >=
        `v6`](https://codesandbox.io/p/sandbox/fabric-node-sandbox-forked-xewlhg?file=%2FREADME.md),
        [Node template <
        `v6`](https://codesandbox.io/p/sandbox/fabric-node-sandbox-forked-ddztl5?file=%2FREADME.md)

        â›” No reproduction === closed issue â›”
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
      render: bash
    validations:
      required: false
