name: 🔓 Feature Request
description: File a feature request
title: '[Feature]: '
body:
  - type: markdown
    attributes:
      value: >
        Thank you for wanting to contribute to this repository. 

        Before you do, please ensure you are filing the ticket in the right
        place. 

        If you have a question use
        [Discussions](../discussions).

        If you are up for contributing see [CONTRIBUTING](CONTRIBUTING.md)
  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: >-
        By submitting this ticket, you agree to follow our [Code of
        Conduct](../blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: >-
            I have read and followed the [Contributing
            Guide](../blob/master/CONTRIBUTING.md)
          required: true
        - label: >-
            I have read and followed the [Issue Tracker
            Guide](../blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
          required: true
        - label: I have searched and referenced existing issues and discussions
          required: true
        - label: I am filing a **FEATURE** request.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Detail your suggestion and the desired behavior.
        Provide screenshots/screencasts if relevant.
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current State
      description: Detail current state/behavior and existing solutions/workarounds
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide additional context
    validations:
      required: false
