import { defineConfig } from 'astro/config';
import react from "@astrojs/react";
import starlight from "@astrojs/starlight";
import starlightTypeDoc, { typeDocSidebarGroup } from 'starlight-typedoc';
import fs from 'node:fs'

import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://fabricjs.com',
  redirects: {
    '/kitchensink': 'https://fabric5.fabricjs.com/kitchensink',
    '/fabric-object-caching': '/docs/fabric-object-caching',
    '/docs/old-docs/fabric-object-caching': '/docs/fabric-object-caching',
  },
  integrations: [starlight({
    favicon: '/favicon.ico',
    title: 'Docs and Guides',
    disable404Route: true, 
    logo: {
      src: './src/assets/logo.svg',
    },
    components: {
      Header: './src/components/Header/HeaderWithSearch.astro',
      PageTitle: './src/components/PageTitleDocs/PageTitle.astro',
    },
    sidebar: [
      {
        label: 'Docs',
        // Collapse the group and its autogenerated subgroups by default.
        collapsed: true,
        autogenerate: { directory: 'docs' },
      },
      {
        label: 'Api',
        // Collapse the group and its autogenerated subgroups by default.
        collapsed: true,
        autogenerate: { directory: 'api' },
      },
      {
        label: 'Fabric.js v5',
        link: 'https://fabric5.fabricjs.com/docs',
      }
    ],
    customCss: [
      // Relative path to your custom CSS file
      './src/layouts/colorvars.css',
    ],
    plugins: [
      // Generate the documentation only if local sources exist.
      // This avoids dev crashes when `fabric.js` sources are not checked out.
      (fs.existsSync(new URL('./fabric.js/fabric.ts', import.meta.url)) &&
       fs.existsSync(new URL('./fabric.js/typedoc.config.json', import.meta.url))) &&
        starlightTypeDoc({
          entryPoints: ['./fabric.js/fabric.ts'],
          tsconfig: './fabric.js/typedoc.config.json',
          typeDoc: {
            plugin: ['typedoc-plugin-no-inherit'],
            readme: 'none',
            gitRemote: 'https://github.com/fabricjs/fabric.js/blob',
            entryFileName: 'index.md',
            includeVersion: true,
            sourceLinkExternal: true,
            sourceLinkTemplate: 'https://github.com/fabricjs/fabric.js/blob/{gitRevision}/{path}#L{line}',
          },
        }),
    ].filter(Boolean),
  }), react(), sitemap()],
});