# This workflow will install Uglify and verify that fabric can be build with it

name: Building with uglify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Uglyfied build
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install uglify-js@3.3.x
    - run: npm run build
