name: changelog

on:
  pull_request:
    branches: [master]
    types: [opened, edited]

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      file: CHANGELOG.md
      next_version: next
      log: '- ${{ github.event.pull_request.title }} [#${{ github.event.number }}](https://github.com/fabricjs/fabric.js/pull/${{ github.event.number }})'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Check ${{ env.file }}
        id: check
        continue-on-error: true
        run: |
          if [[ $(git diff --name-only origin/master HEAD -- ${{ env.file }} | grep '^${{ env.file }}$' -c) -eq 0 ]]; then
            echo "Expected '${{ env.file }}' to be modified"
            exit 1
          fi
      - name: Update ${{ env.file }}
        id: update
        if: (github.action != 'edited' || github.event.changes.title.from != github.event.pull_request.title) && (steps.check.outcome == 'success' || steps.check.outcome == 'failure')
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const file = './${{ env.file }}';
            let content = fs.readFileSync(file).toString();
            const title = '[${{ env.next_version }}]';
            const log = '${{ env.log }}\n';
            let exists = ${{ steps.check.outcome == 'success' }};

            if (!content.includes(title)) {
            const insertAt = content.indexOf('\n') + 1;
            content =
                content.slice(0, insertAt) +
                `\n## ${title}\n\n\n` +
                content.slice(insertAt);
            }

            const insertAt = content.indexOf('\n', `${title}\n`) + 1;
            const index = content.indexOf(log, insertAt);
            if (index > -1) {
                content = content.slice(0, index) + content.slice(index);
                exists = false;
            }

            console.log(exists, content)
            if (!exists) {
                console.log(content)
                content = content.slice(0, insertAt) + log + content.slice(insertAt);
                fs.writeFileSync(file, content);
                return true;
            }

            return false;
      - name: Commit & Push
        if: steps.update.outputs.result
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add ${{ env.file }}
          git commit -m "update ${{ env.file }}"
          git push
