name: 'Auto 📋'

on:
  pull_request:
    branches: [master]
    types: [opened, edited]

jobs:
  check:
    uses: ./.github/workflows/changelog.yml
  update:
    runs-on: ubuntu-latest
    needs: check
    if: failure() && (github.event.action == 'opened' || (success() && github.event.changes.title.from != github.event.pull_request.title))
    env:
      file: CHANGELOG.md
      next_version: next
      link: '[#${{ github.event.number }}](https://github.com/fabricjs/fabric.js/pull/${{ github.event.number }})'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update ${{ env.file }} from PR title
        id: update
        uses: actions/github-script@v6
        env:
          log: '- ${{ github.event.pull_request.title }} ${{ env.link }}\n'
          prev_log: '- ${{ github.event.changes.title.from }} ${{ env.link }}\n'
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            const file = './${{ env.file }}';
            let content = fs.readFileSync(file).toString();
            const title = '[${{ env.next_version }}]';
            const log = '${{ env.log }}';
            let exists = ${{ needs.check.result == 'success' }};

            if (!content.includes(title)) {
            const insertAt = content.indexOf('\n') + 1;
            content =
                content.slice(0, insertAt) +
                `\n## ${title}\n\n\n` +
                content.slice(insertAt);
            }

            const insertAt = content.indexOf('\n', content.indexOf(title) + title.length + 1) + 1;
            if (exists && ${{ github.event.action == 'edited' }}) {
                const prevLog = '${{ env.prev_log }}';
                const index = content.indexOf(prevLog, insertAt);
                if (index > -1) {
                    content = content.slice(0, index) + content.slice(index + prevLog.length);
                    exists = false;
                }
            }

            if (!exists) {
                content = content.slice(0, insertAt) + log + content.slice(insertAt);
                fs.writeFileSync(file, content);
                execSync(`prettier --write ${file}`);
                return true;
            }

            return false;
      - name: Commit & Push
        if: steps.update.outputs.result
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add ${{ env.file }}
          git commit -m "update ${{ env.file }}"
          git push
