name: Changelog

on:
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      file: CHANGELOG.md
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check ${{ env.file }}
        id: check
        run: |
          if [[ $(git diff --name-only origin/master HEAD -- ${{ env.file }} | grep '^${{ env.file }}$' -c) -eq 0 ]]; then
            echo "Expected '${{ env.file }}' to be modified"
            exit 1
          fi
