# This workflow will install eslint and lint the code.
name: Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install eslint@4.7.x
    - run: npm run lint
