name: Node.js Package

on:
  release:
    branches:
      - master
      - 5.x
      - 6.x
    types: [published]
permissions:
  contents: read
jobs:
  publish-npm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: node publish.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          PRE_RELEASE: ${{ github.event.release.prerelease }}
          TAG_NAME: ${{ github.event.release.tag_name }}
