
name: Node Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x] 
        suites: [unit, visual]
    steps:
    - uses: actions/checkout@v2
    - name: Install node-canvas
      run: sudo apt-get install libgif-dev libpng-dev libpango1.0-dev libjpeg8-dev librsvg2-dev libcairo2-dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Build
      run: npm run build -- -f
    - name: Run ${{ matrix.suite }} tests
      run: npm run test -- -c node -s ${{ matrix.suite }} 
