# This workflow will do a clean install of node dependencies, build the library, run testem for chrome

name: Browser Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  chrome-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        suite: [unit, visual]
        target: [chrome, firefox]
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests on Chrome
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build -- -f
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test -- -s ${{ matrix.suite }} -c ${{ matrix.target }}
