
name: Browser Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        target: [chrome, firefox]
        suite: [unit, visual]
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests on Chrome
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build -- -f
    - name: Run ${{ matrix.target }} ${{ matrix.suite }} headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test -- -c ${{ matrix.target }} -s ${{ matrix.suite }}
